"""Milestone 0 rig emitter: RigSpec -> standalone TypeScript.

Turns a hand-written RigSpec (forge/stage5_rig/rig_spec.py) plus a small side
channel of component bounding-box extents into a self-contained .ts module
that builds a real THREE.Bone hierarchy + THREE.Skeleton, skins a single
capsule mesh with the weight function from PLAN_1.5 §4, and binds it.

Standalone on purpose. Does NOT import from or get called by
generate_threejs_factory.py — integration is a later milestone, and that file
is dirty in this checkout.

MILESTONE-0 SCOPE NOTE: the geometry this emitter builds is a synthetic
watertight capsule constructed directly from the bone chain span, not a
subject-derived mesh from the real pipeline (stage1/stage2 output). Wiring
this weight function to real emitted geometry is future work; this file only
answers "can a generator emit a working skinned rig from a spec at all."

MILESTONE-0 SIMPLIFICATION: the capsule builder assumes the bone chain is a
single straight line along local +Y/-Y (matching the capsule's own
construction axis). Off-axis or branching chains are out of scope here.

Pure Python 3.10+ stdlib. No pip installs, no string.Template brace-escaping
footguns — plain token replacement is used instead of str.format()/f-strings
against the JS/TS body, because that body is full of literal `{`/`}`.
"""

from __future__ import annotations

import json
import math
from typing import Optional

from .rig_spec import BoneSpec, RigSpec, derive_envelope_radius, validate_rig_spec

_TEMPLATE = r"""// AUTO-GENERATED by forge/stage5_rig/emit_rig.py — Milestone 0 rig kill test.
// Do not hand-edit; regenerate from the RigSpec instead.
import * as THREE from 'three';

// ---------------------------------------------------------------------------
// RigSpec-derived constants. Every number below traces to the hand-written
// RigSpec and the derived-not-proposed envelope radius formula (PLAN_1.5 §4.3).
// ---------------------------------------------------------------------------
export const BONE_IDS = __BONE_IDS_JSON__;
export const PARENT = __PARENT_JSON__;
export const JOINT_POS = __JOINT_POS_JSON__;
export const TIP_POS = __TIP_POS_JSON__;
export const ENVELOPE_RADIUS = __ENVELOPE_RADIUS_JSON__;
export const OVERLAP_FACTOR = __OVERLAP_FACTOR__;

const CAPSULE_RADIUS = __CAPSULE_RADIUS__;
const CAPSULE_CYL_LENGTH = __CAPSULE_CYL_LENGTH__;
const CAPSULE_CENTER_Y = __CAPSULE_CENTER_Y__;
const CAP_SEGMENTS = __CAP_SEGMENTS__;
const RADIAL_SEGMENTS = __RADIAL_SEGMENTS__;
const HEIGHT_SEGMENTS = __HEIGHT_SEGMENTS__;

// ---------------------------------------------------------------------------
// Watertight-by-construction capsule: shared pole vertices, modulo-wrapped
// radial rings (no UV-seam vertex duplication). three@0.169's own
// THREE.CapsuleGeometry was measured (during design of this emitter) to leave
// ~98 boundary edges even after BufferGeometryUtils.mergeVertices on a
// position-only copy of it, because its radial seam column is a genuine
// second set of vertex indices at (numerically, not exactly) the same
// position that a 1e-5 weld does not always collapse cleanly at the poles.
// Building the grid so the seam never exists (radial index taken mod
// RADIAL_SEGMENTS) sidesteps that fragility entirely and is exact, not
// tolerance-dependent.
//
// heightSegments subdivides the CYLINDRICAL band into multiple rings (not
// just the two equators). Without this, a single quad band spans the whole
// cylinder and no vertex sits anywhere near an interior bone's pivot, which
// silently defeats a pose-sweep gate: rotating a joint whose bone segment
// lies entirely inside that one quad band only swings a rigid cap, never
// actually samples deformation near the joint. heightSegments is chosen by
// the caller (see emit_typescript()) from the derived envelope radius, not
// hardcoded here.
// ---------------------------------------------------------------------------
function buildWatertightCapsule(radius, cylLength, capSegments, radialSegments, heightSegments) {
  const positions = [];
  const indices = [];
  const halfCyl = cylLength / 2;

  const bottomPoleIndex = positions.length / 3;
  positions.push(0, -halfCyl - radius, 0);

  const ringStarts = [];
  for (let ring = 1; ring <= capSegments; ring++) {
    const phi = (Math.PI / 2) * (ring / capSegments);
    const y = -halfCyl - radius * Math.cos(phi);
    const r = radius * Math.sin(phi);
    const start = positions.length / 3;
    ringStarts.push(start);
    for (let radial = 0; radial < radialSegments; radial++) {
      const theta = (radial / radialSegments) * Math.PI * 2;
      positions.push(r * Math.cos(theta), y, r * Math.sin(theta));
    }
  }

  // Cylinder rings: heightSegments steps from the bottom equator (already the
  // last entry of ringStarts, at y=-halfCyl) up to and including the top
  // equator (y=+halfCyl). This is what puts real geometry along the whole
  // shaft, not just at its two ends.
  const cylinderRingStarts = [];
  if (cylLength > 0) {
    for (let step = 1; step <= heightSegments; step++) {
      const y = -halfCyl + (cylLength * step) / heightSegments;
      const start = positions.length / 3;
      cylinderRingStarts.push(start);
      for (let radial = 0; radial < radialSegments; radial++) {
        const theta = (radial / radialSegments) * Math.PI * 2;
        positions.push(radius * Math.cos(theta), y, radius * Math.sin(theta));
      }
    }
  }
  const topEquatorStart = cylLength > 0
    ? cylinderRingStarts[cylinderRingStarts.length - 1]
    : ringStarts[ringStarts.length - 1];

  const topRingStarts = [];
  for (let ring = capSegments - 1; ring >= 1; ring--) {
    const phi = (Math.PI / 2) * (ring / capSegments);
    const y = halfCyl + radius * Math.cos(phi);
    const r = radius * Math.sin(phi);
    const start = positions.length / 3;
    topRingStarts.push(start);
    for (let radial = 0; radial < radialSegments; radial++) {
      const theta = (radial / radialSegments) * Math.PI * 2;
      positions.push(r * Math.cos(theta), y, r * Math.sin(theta));
    }
  }

  const topPoleIndex = positions.length / 3;
  positions.push(0, halfCyl + radius, 0);

  const firstBottomRing = ringStarts[0];
  for (let radial = 0; radial < radialSegments; radial++) {
    const next = (radial + 1) % radialSegments;
    indices.push(bottomPoleIndex, firstBottomRing + radial, firstBottomRing + next);
  }

  const allRings = [...ringStarts, ...cylinderRingStarts, ...topRingStarts];
  for (let i = 0; i < allRings.length - 1; i++) {
    const a = allRings[i];
    const b = allRings[i + 1];
    for (let radial = 0; radial < radialSegments; radial++) {
      const next = (radial + 1) % radialSegments;
      indices.push(a + radial, a + next, b + next);
      indices.push(a + radial, b + next, b + radial);
    }
  }

  const lastRing = allRings[allRings.length - 1];
  for (let radial = 0; radial < radialSegments; radial++) {
    const next = (radial + 1) % radialSegments;
    indices.push(topPoleIndex, lastRing + next, lastRing + radial);
  }

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(new Float32Array(positions), 3));
  geometry.setIndex(indices);
  return geometry;
}

// ---------------------------------------------------------------------------
// PLAN_1.5 §4 weight function — the ONE function, evaluated over the
// complete bone set, for every mesh. No mesh-id / vertex-index branching:
// only positions, the segment endpoints, and the derived envelope radius.
// ---------------------------------------------------------------------------
const _closestScratch = new THREE.Vector3();
function closestPointOnSegment(p, s, e, out) {
  const abx = e[0] - s[0];
  const aby = e[1] - s[1];
  const abz = e[2] - s[2];
  const apx = p.x - s[0];
  const apy = p.y - s[1];
  const apz = p.z - s[2];
  const abLenSq = abx * abx + aby * aby + abz * abz;
  const t = abLenSq > 1e-12
    ? THREE.MathUtils.clamp((apx * abx + apy * aby + apz * abz) / abLenSq, 0, 1)
    : 0;
  out.set(s[0] + abx * t, s[1] + aby * t, s[2] + abz * t);
  return out;
}

function distanceToSegment(p, s, e) {
  closestPointOnSegment(p, s, e, _closestScratch);
  return p.distanceTo(_closestScratch);
}

/** Returns { indices: number[4], weights: number[4], fallback: boolean }. */
function computeVertexWeights(p, boneIndexOf) {
  const scored = BONE_IDS.map((id) => {
    const d = distanceToSegment(p, JOINT_POS[id], TIP_POS[id]);
    const u = d / ENVELOPE_RADIUS[id];
    const w = Math.max(0, 1 - u * u) ** 2;
    return { id, d, w };
  });
  scored.sort((a, b) => b.w - a.w);
  const kept = scored.slice(0, 4);
  const total = kept.reduce((sum, c) => sum + c.w, 0);

  const indices = [0, 0, 0, 0];
  const weights = [0, 0, 0, 0];

  if (total > 0) {
    for (let slot = 0; slot < 4; slot++) {
      if (slot < kept.length) {
        indices[slot] = boneIndexOf.get(kept[slot].id);
        weights[slot] = kept[slot].w / total;
      }
    }
    return { indices, weights, fallback: false };
  }

  // Mandatory zero-sum fallback (PLAN_1.5 §4 / ADR-8): every kept weight is
  // zero (vertex outside every envelope). three.js's own
  // normalizeSkinWeights() would otherwise rewrite this to (1,0,0,0) against
  // bone 0 regardless of distance. Instead: find the absolutely nearest bone
  // ignoring R_b and pin weight 1.0 to it.
  let nearestId = BONE_IDS[0];
  let nearestDistance = Infinity;
  for (const id of BONE_IDS) {
    const d = distanceToSegment(p, JOINT_POS[id], TIP_POS[id]);
    if (d < nearestDistance) {
      nearestDistance = d;
      nearestId = id;
    }
  }
  indices[0] = boneIndexOf.get(nearestId);
  weights[0] = 1;
  return { indices, weights, fallback: true };
}

export function createRigMilestone0() {
  const bones = {};
  for (const id of BONE_IDS) {
    bones[id] = new THREE.Bone();
    bones[id].name = id;
  }
  let root = null;
  for (const id of BONE_IDS) {
    const parentId = PARENT[id];
    const j = JOINT_POS[id];
    if (parentId === null) {
      root = bones[id];
      bones[id].position.set(j[0], j[1], j[2]);
    } else {
      const pj = JOINT_POS[parentId];
      bones[id].position.set(j[0] - pj[0], j[1] - pj[1], j[2] - pj[2]);
      bones[parentId].add(bones[id]);
    }
  }

  const geometry = buildWatertightCapsule(CAPSULE_RADIUS, CAPSULE_CYL_LENGTH, CAP_SEGMENTS, RADIAL_SEGMENTS, HEIGHT_SEGMENTS);
  geometry.translate(0, CAPSULE_CENTER_Y, 0);

  const boneIndexOf = new Map(BONE_IDS.map((id, i) => [id, i]));
  const position = geometry.getAttribute('position');
  const skinIndices = new Uint16Array(position.count * 4);
  const skinWeights = new Float32Array(position.count * 4);
  const fallbackVertices = [];
  const point = new THREE.Vector3();
  for (let vertex = 0; vertex < position.count; vertex++) {
    point.fromBufferAttribute(position, vertex);
    const { indices, weights, fallback } = computeVertexWeights(point, boneIndexOf);
    for (let slot = 0; slot < 4; slot++) {
      skinIndices[vertex * 4 + slot] = indices[slot];
      skinWeights[vertex * 4 + slot] = weights[slot];
    }
    if (fallback) fallbackVertices.push(vertex);
  }
  geometry.setAttribute('skinIndex', new THREE.Uint16BufferAttribute(skinIndices, 4));
  geometry.setAttribute('skinWeight', new THREE.Float32BufferAttribute(skinWeights, 4));
  geometry.computeVertexNormals();
  geometry.computeBoundingBox();
  geometry.computeBoundingSphere();

  const mesh = new THREE.SkinnedMesh(geometry, new THREE.MeshBasicMaterial());
  mesh.name = 'rig-milestone0-arm';
  // AttachedBindMode (the default) requires the skeleton to share the mesh's
  // world space, which requires the root bone to be a child of the mesh, not
  // a sibling. Learned from createRiggedDragon.ts (`body.add(bones.root)`).
  mesh.add(root);
  const skeleton = new THREE.Skeleton(BONE_IDS.map((id) => bones[id]));
  mesh.bindMode = THREE.AttachedBindMode;
  mesh.bind(skeleton);

  return {
    mesh,
    skeleton,
    bones,
    meta: {
      envelopeRadius: ENVELOPE_RADIUS,
      jointPos: JOINT_POS,
      tipPos: TIP_POS,
      fallbackVertices,
    },
  };
}
"""


def _fmt_num(value: float) -> str:
    if float(value).is_integer():
        return repr(float(value))
    return repr(float(value))


# PLAN_1.5 §4's weight function is continuous, so it must actually be SAMPLED
# at a resolution finer than the smallest envelope radius in play, or a
# pose-sweep gate can silently test nothing near a joint (see
# emit_typescript()'s height_segments derivation below, and the Milestone 0
# report for the concrete failure this caught: a single quad band spanning
# the whole cylinder let the elbow's influenced region skip past the pivot
# entirely). 3 is not tuned per RigSpec; it is a fixed, stated ratio applied
# uniformly to whatever envelope radius the spec/components produce.
RING_RESOLUTION_DIVISOR = 3.0


def emit_typescript(
    spec: RigSpec,
    component_extents: dict[str, tuple[float, float]],
    capsule_radius: float,
    overlap_factor: float = 1.2,
    cap_segments: int = 8,
    radial_segments: int = 16,
    height_segments: Optional[int] = None,
) -> str:
    """Emit the Milestone 0 TypeScript module for `spec`.

    `height_segments` subdivides the capsule's cylindrical band lengthwise.
    Left as None (the default), it is DERIVED — not hand-picked per spec —
    from the smallest derived envelope radius in play, at
    RING_RESOLUTION_DIVISOR rings per radius, so every bone's influence band
    is guaranteed several rings of real geometry rather than risking a single
    quad spanning past it. Pass an explicit value only to override for
    testing.

    Fails closed (raises ValueError) on:
      - a RigSpec that does not pass validate_rig_spec()
      - a bone chain that is not a straight vertical line (the milestone-0
        capsule-construction simplification stated in this module's docstring)
      - a bone referencing a component id missing from component_extents
    """
    errors = validate_rig_spec(spec)
    if errors:
        raise ValueError("RigSpec rejected by validate_rig_spec: " + "; ".join(errors))

    tip_pos = spec.resolve_tip_positions()
    joint_pos = {b.id: b.joint_pos for b in spec.bones}
    parent = {b.id: b.parent for b in spec.bones}
    bone_ids = [b.id for b in spec.bones]

    envelope_radius: dict[str, float] = {}
    by_id: dict[str, BoneSpec] = spec.bone_by_id()
    for bone in spec.bones:
        if bone.component is None:
            raise ValueError(f"bone '{bone.id}' has no component; cannot derive envelope radius")
        if bone.component not in component_extents:
            raise ValueError(
                f"bone '{bone.id}' references component '{bone.component}' "
                f"which is not present in component_extents"
            )
        width, depth = component_extents[bone.component]
        envelope_radius[bone.id] = derive_envelope_radius(width, depth, overlap_factor)

    # Milestone-0 simplification check: every joint/tip position must lie on
    # a single straight vertical (Y-axis) line, matching the capsule builder.
    all_points = [joint_pos[b] for b in bone_ids] + [tip_pos[b] for b in bone_ids]
    xs = {round(p[0], 9) for p in all_points}
    zs = {round(p[2], 9) for p in all_points}
    if len(xs) != 1 or len(zs) != 1:
        raise ValueError(
            "Milestone-0 capsule builder requires a straight chain along the Y axis "
            "(constant x and z across every jointPos/tipPos); this RigSpec is not one. "
            "This is a stated milestone-0 scope limit, not a general capability."
        )

    root_bone = spec.root()
    chain_top_y = root_bone.joint_pos[1]
    leaf_ids = [b.id for b in spec.bones if not spec.children_of(b.id)]
    if len(leaf_ids) != 1:
        raise ValueError(
            f"Milestone-0 capsule builder requires exactly one leaf bone (a single "
            f"linear chain), found {len(leaf_ids)}: {leaf_ids}"
        )
    chain_bottom_y = tip_pos[leaf_ids[0]][1]
    total_length = abs(chain_top_y - chain_bottom_y)
    cyl_length = total_length - 2 * capsule_radius
    if cyl_length <= 0:
        raise ValueError(
            f"capsule_radius {capsule_radius} is too large for chain length {total_length}: "
            f"cylindrical section would be non-positive ({cyl_length})"
        )
    center_y = (chain_top_y + chain_bottom_y) / 2

    if height_segments is None:
        target_ring_spacing = min(envelope_radius.values()) / RING_RESOLUTION_DIVISOR
        height_segments = max(4, math.ceil(cyl_length / target_ring_spacing))

    replacements = {
        "__BONE_IDS_JSON__": json.dumps(bone_ids),
        "__PARENT_JSON__": json.dumps(parent),
        "__JOINT_POS_JSON__": json.dumps(joint_pos),
        "__TIP_POS_JSON__": json.dumps(tip_pos),
        "__ENVELOPE_RADIUS_JSON__": json.dumps(envelope_radius),
        "__OVERLAP_FACTOR__": _fmt_num(overlap_factor),
        "__CAPSULE_RADIUS__": _fmt_num(capsule_radius),
        "__CAPSULE_CYL_LENGTH__": _fmt_num(cyl_length),
        "__CAPSULE_CENTER_Y__": _fmt_num(center_y),
        "__CAP_SEGMENTS__": str(int(cap_segments)),
        "__RADIAL_SEGMENTS__": str(int(radial_segments)),
        "__HEIGHT_SEGMENTS__": str(int(height_segments)),
    }
    source = _TEMPLATE
    for token, value in replacements.items():
        if token not in source:
            raise AssertionError(f"template token {token} not found — template/replacement drift")
        source = source.replace(token, value)
    return source
